name: Delete Old Releases

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          keep_latest: 5
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
